host: custom

# Defining CI tasks for Waffle here instead of implementing via a workflow.
tasks:
  # Defining a task to run the phpcs script.
  test-phpcs: ./scripts/tests/phpcs.sh
  test-bats: "./vendor/bats-core/bats-core/bin/bats tests/bats/bats"

recipes:
  # Defining a ci recipe.
  ci:
    - test-phpcs: {}
    - test-bats: {}
