services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    Waffle\Command\DiscoverableCommandInterface:
      tags: ['commands']
    Waffle\Command\DiscoverableTaskInterface:
      tags: ['tasks']
    Waffle\Command\DiscoverableRecipeInterface:
      tags: ['recipes']

  Waffle\:
    lazy: true
    resource: '../src'

  Waffle\Application:
    public: true

  Waffle\Model\Command\CommandManager:
    public: true
    arguments:
      - !tagged commands



