services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    Waffle\Model\Config\ConfigItemInterface:
      tags: ['config_items']
    Waffle\Command\DiscoverableCommandInterface:
      tags: ['commands']
    Waffle\Command\DiscoverableTaskInterface:
      tags: ['tasks']
    Waffle\Command\DiscoverableRecipeInterface:
      tags: ['recipes']

  Waffle\:
    lazy: true
    resource: '../src'

  Waffle\Application:
    public: true

  Waffle\Model\Config\ConfigTreeService:
    public: true
    arguments:
      - !tagged config_items

  Waffle\Model\Command\CommandManager:
    public: true
    arguments:
      - !tagged commands

  Waffle\Model\Command\TaskManager:
    public: true
    arguments:
      - '@Waffle\Model\Context\Context'
      - !tagged tasks

  Waffle\Model\Command\RecipeManager:
    public: true
    arguments:
      - '@Waffle\Model\Context\Context'
      - !tagged recipes
