# Workflow to run the 'ci' task defined in .waffle.yml.
on: [push, pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.0']
    name: PHP ${{ matrix.php-versions }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Run PHPCS
      run: |
          composer install
          bin/wfl recipe:ci
